Repository artrixdotdev/tortillas, pull requests merged in 2025-07, with the labels that each got.

#63 refactor: Repo cleanup
  .github/workflows/checks.yml
  CONTRIBUTING.md
  Cargo.lock
  Cargo.toml
  README.md
  crates/libtortillas/Cargo.toml
  crates/libtortillas/src/engine/mod.rs
  crates/libtortillas/src/errors.rs
  crates/libtortillas/src/hashes.rs
  crates/libtortillas/src/parser/file.rs
  crates/libtortillas/src/parser/magnet.rs
  crates/libtortillas/src/parser/mod.rs
  crates/libtortillas/src/peers/commands.rs
  crates/libtortillas/src/peers/messages.rs
  crates/libtortillas/src/peers/mod.rs
  crates/libtortillas/src/peers/stream.rs
  crates/libtortillas/src/tracker/http.rs
  crates/libtortillas/src/tracker/mod.rs
  crates/libtortillas/src/tracker/udp.rs
  crates/tortillas/Cargo.toml
  crates/tortillas/README.md
  rustfmt.toml
Labels: docs, low prio

#66 feat: Library housekeeping & engine creation
  .github/workflows/checks.yml
  CONTRIBUTING.md
  Cargo.lock
  Cargo.toml
  README.md
  crates/libtortillas/Cargo.toml
  crates/libtortillas/src/engine/mod.rs
  crates/libtortillas/src/errors.rs
  crates/libtortillas/src/hashes.rs
  crates/libtortillas/src/lib.rs
  crates/libtortillas/src/parser/file.rs
  crates/libtortillas/src/parser/magnet.rs
  crates/libtortillas/src/parser/mod.rs
  crates/libtortillas/src/peers/messages.rs
  crates/libtortillas/src/peers/mod.rs
  crates/libtortillas/src/peers/peer/info.rs
  crates/libtortillas/src/peers/peer/mod.rs
  crates/libtortillas/src/peers/peer/state.rs
  crates/libtortillas/src/peers/peer/supports.rs
  crates/libtortillas/src/peers/peer_comms/commands.rs
  crates/libtortillas/src/peers/peer_comms/messages.rs
  crates/libtortillas/src/peers/peer_comms/mod.rs
  crates/libtortillas/src/peers/peer_comms/stream.rs
  crates/libtortillas/src/peers/tcp.rs
  crates/libtortillas/src/peers/transport_messages.rs
  crates/libtortillas/src/peers/utp.rs
  crates/libtortillas/src/tracker/http.rs
  crates/libtortillas/src/tracker/mod.rs
  crates/libtortillas/src/tracker/udp.rs
  crates/tortillas/Cargo.toml
  crates/tortillas/README.md
  rustfmt.toml
Labels: high prio

#70 test: Change torrents
  crates/libtortillas/src/engine/mod.rs
  crates/libtortillas/src/peers/mod.rs
  crates/libtortillas/src/tracker/http.rs
  crates/libtortillas/tests/magneturis/cachyos-desktop-linux-250713.txt
  crates/libtortillas/tests/magneturis/test1.txt
  crates/libtortillas/tests/magneturis/wired-cd.txt
  crates/libtortillas/tests/magneturis/zenshuu.txt
  crates/libtortillas/tests/torrents/archlinux-2025.07.01-x86_64.iso.torrent
  crates/libtortillas/tests/torrents/wired-cd.torrent
Labels: enhancement, med prio
