Repository artrixdotdev/tortillas, pull requests merged in 2025-08, with the labels that each got.

#80 feat: Add peer ID parsing and serialization
  crates/libtortillas/src/engine/mod.rs
  crates/libtortillas/src/peers/mod.rs
  crates/libtortillas/src/peers/peer/id.rs
  crates/libtortillas/src/peers/peer/mod.rs
  crates/libtortillas/src/peers/peer_comms/messages.rs
  crates/libtortillas/src/peers/peer_comms/stream.rs
  crates/libtortillas/src/tracker/http.rs
  crates/libtortillas/src/tracker/mod.rs
  crates/libtortillas/src/tracker/udp.rs
Labels: high prio

#92 feat: Add Torrent struct
  crates/libtortillas/src/errors.rs
  crates/libtortillas/src/lib.rs
  crates/libtortillas/src/protocol/mod.rs
  crates/libtortillas/src/torrent/mod.rs
  crates/libtortillas/src/tracker/mod.rs
  crates/libtortillas/src/util.rs
Labels: enhancement, high prio, med prio

#93 refactor: Move to dashmap
  Cargo.lock
  crates/libtortillas/Cargo.toml
  crates/libtortillas/src/tracker/udp.rs
Labels: high prio

#107 feat: Implement `add_torrent`
  crates/libtortillas/src/engine/mod.rs
  crates/libtortillas/src/errors.rs
Labels: enhancement, med prio

#121 perf: Changed all uses of BitVec to Arc<BitVec>
  crates/libtortillas/src/peer/actor.rs
  crates/libtortillas/src/peer/mod.rs
  crates/libtortillas/src/protocol/messages.rs
  crates/libtortillas/src/torrent/mod.rs
Labels: enhancement, high prio

#125 refactor: High level API for `Torrent` and `Engine`
  Cargo.lock
  crates/libtortillas/Cargo.toml
  crates/libtortillas/src/engine/actor.rs
  crates/libtortillas/src/engine/messages.rs
  crates/libtortillas/src/engine/mod.rs
  crates/libtortillas/src/errors.rs
  crates/libtortillas/src/lib.rs
  crates/libtortillas/src/peer/actor.rs
  crates/libtortillas/src/torrent/actor.rs
  crates/libtortillas/src/torrent/messages.rs
  crates/libtortillas/src/torrent/mod.rs
  crates/libtortillas/src/tracker/http.rs
  crates/libtortillas/src/tracker/mod.rs
Labels: enhancement, high prio, refactor
