Repository artrixdotdev/tortillas, pull requests merged in 2025-09, with the labels that each got.

#147 chore: Updated tracing-subscriber and related deps
  Cargo.lock
Labels: low prio

#144 ci: Release `libtortillas` to crates.io on merge to main branch
  .github/workflows/checks.yml
  .github/workflows/release.yml
  crates/libtortillas/Cargo.toml
Labels: high prio

#148 fix: toctou bug in message handling
  crates/libtortillas/src/engine/messages.rs
Labels: bug, med prio

#149 feat: Make mailbox sizes configurable with sensible defaults
  crates/libtortillas/src/engine/actor.rs
  crates/libtortillas/src/engine/messages.rs
  crates/libtortillas/src/engine/mod.rs
Labels: enhancement, med prio

#150 feat: Implement a blocking start method & auto starting functionality
  crates/libtortillas/src/engine/actor.rs
  crates/libtortillas/src/engine/messages.rs
  crates/libtortillas/src/engine/mod.rs
  crates/libtortillas/src/torrent/actor.rs
  crates/libtortillas/src/torrent/messages.rs
  crates/libtortillas/src/torrent/mod.rs
Labels: enhancement, high prio
